[colors.primary]
background = "#010b17"
foreground = "#ebddf4"

[colors.cursor]
text = "#010b17"
cursor = "#15fca2"

[colors.normal]
black = "#0b3b61"
red = "#ff3a3a"
green = "#52ffcf"
yellow = "#fff383"
blue = "#1376f8"
magenta = "#c792ea"
cyan = "#ff5dd4"
white = "#8f9bb3"

[colors.bright]
black = "#62686c"
red = "#ff54b0"
green = "#73ffd8"
yellow = "#fcf4ad"
blue = "#378dfe"
magenta = "#ae81ff"
cyan = "#ff69d7"
white = "#ebddf4"
