$base = rgb(010b17)
$mantle = rgb(011429)
$surface0 = rgb(0b3b61)
$surface1 = rgb(135080)
$surface2 = rgb(62686c)
$text = rgb(ebddf4)
$subtext0 = rgb(b3a8d1)
$subtext1 = rgb(d1c4e6)
$overlay0 = rgb(8f9bb3)
$blue = rgb(378dfe)
$green = rgb(52ffcf)
$red = rgb(ff3a3a)
$yellow = rgb(fff383)
$yellow_bright = rgb(fcf4ad)
$peach = rgb(ff69d7)
$mauve = rgb(ae81ff)
$teal = rgb(15fca2)
$orange = rgb(ff5dd4)
