set -g status-style bg="#011429",fg="#ebddf4"
set -g pane-border-style fg="#0b3b61"
set -g pane-active-border-style fg="#15fca2"
set -g window-status-current-style bg="#378dfe",fg="#010b17",bold
set -g message-style bg="#fff383",fg="#010b17"
