[manager]
cwd = { fg = "#15fca2" }
hovered = { reversed = true }
preview_hovered = { reversed = true }
find_keyword = { fg = "#fff383", italic = true }
find_position = { fg = "#ae81ff", bg = "reset", italic = true }
marker_selected = { fg = "#52ffcf", bg = "#52ffcf" }
marker_copied = { fg = "#fff383", bg = "#fff383" }
marker_cut = { fg = "#ff3a3a", bg = "#ff3a3a" }
tab_active = { fg = "#010b17", bg = "#378dfe" }
tab_inactive = { fg = "#ebddf4", bg = "#0b3b61" }
border_symbol = "│"
border_style = { fg = "#135080" }
